config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users

  get "/books/my_books", to: "books#my_books", as: :my_books_book
  resources :books

  # Defines the root path route ("/")
  root "books#index"

  # resources
  # get "/books", to: "books#index", as :books
  # get "/books/new", to: "books#new", as: :new_book
  # get "/books/:id", to: "books#show", as: :book
  # patch "/books/:id", to: "books#update"
  # delete "/books/:id", to: "books#destroy"
  # get "books/:id/edit", to: "books#edit", as: :edit_book
  # post "books/post", to: "books#create", as: :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :author, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	
	before_action :authenticate_user!, except: [:index, :show]
	before_action :set_book, only: [:show, :edit, :update, :destroy]

	def index
		@books = Book.all
	end

	def show
		# error handling when id not found
		rescue ActiveRecord::RecordNotFound
			redirect_to root_path
	end

	def new
		# creates new blog post in memory
		@book = Book.new
		if current_user
			@current_user_email = current_user.email
     		@current_user_id = current_user.id
   		end
	end

	def create
		# saves to database
		@book = Book.new(book_params)
		if current_user
     		@book.update_attribute(:uploaded_by_id, current_user.id)
   		end

		if @book.save
			redirect_to @book
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
	end

	def update
		if @book.update(book_params)
			redirect_to @book
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@book.destroy
		redirect_to root_path
	end

	def my_books
		@books = Book.all
	end

	# Book.new(params[:book]), instead due to security we have to build private method below and permit
	private
	
	def book_params
		params.require(:book).permit(:title, :author)
	end

	def set_book
		@book = Book.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_with model: book do |form| %>
	<% if form.object.errors.any? %>
		<div>
			<% form.object.errors.full_messages.each do |message| %>
				<div><%= message %></div>
			<% end %>
		</div>
	<% end %>
	<div>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</div>

	<div>
		<%= form.label :author %>
		<%= form.text_field :author %>
	</div>

	<%= form.button %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render partial: "form", locals: {book: @book} %>
<%= button_to "Delete", @book, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/books/index.html.erb
<h1>Catalog</h1>

<% @books.each do |book| %>
	<div>
		<h2><%= link_to book.title, book %></h2>
		<%= book.author %>
	</div>
<% end %>

app/views/books/my_books.html.erb
<h1>My Books</h1>

<%= link_to "Add a Book", new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render partial: "form", locals: {book: @book} %>
<p>Uploaded by:<%= @current_user_email %></p>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h2>author: <%= @book.author %></h2>
<p>uploaded by: <%= @book.uploaded_by_id %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookswap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <%= link_to "Home", root_path %>
      <% if user_signed_in? %>
        <%= link_to "Profile", edit_user_registration_path %>
        <%= link_to "My Books", my_books_book_path %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Login", new_user_session_path %>
        <%= link_to "Sign up", new_user_registration_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>